/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortugalMitMichaelRouteImport } from './routes/portugal-mit-michael'
import { Route as PortugalUrlaubRouteImport } from './routes/portugal-urlaub'
import { Route as EHashRouteImport } from './routes/e.$hash'
import { Route as PortugalMitMichaelEditRouteImport } from './routes/portugal-mit-michael.edit'
import { Route as PortugalUrlaubEditRouteImport } from './routes/portugal-urlaub.edit'
import { Route as SHashRouteImport } from './routes/s.$hash'
import { Route as THashRouteImport } from './routes/t.$hash'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiGoogleCallbackRouteImport } from './routes/api/google/callback'
import { Route as ApiGoogleStartRouteImport } from './routes/api/google/start'
import { Route as DHashDayIdRouteImport } from './routes/d.$hash.$dayId'
import { Route as MediaHashIdRouteImport } from './routes/media.$hash.$id'
import { Route as PortugalMitMichaelEditSettingsRouteImport } from './routes/portugal-mit-michael.edit.settings'
import { Route as PortugalUrlaubEditSettingsRouteImport } from './routes/portugal-urlaub.edit.settings'
import { Route as THashEditRouteImport } from './routes/t.$hash.edit'
import { Route as THashEditSettingsRouteImport } from './routes/t.$hash.edit.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortugalMitMichaelRoute = PortugalMitMichaelRouteImport.update({
  id: '/portugal-mit-michael',
  path: '/portugal-mit-michael',
  getParentRoute: () => rootRouteImport,
} as any)
const PortugalUrlaubRoute = PortugalUrlaubRouteImport.update({
  id: '/portugal-urlaub',
  path: '/portugal-urlaub',
  getParentRoute: () => rootRouteImport,
} as any)
const EHashRoute = EHashRouteImport.update({
  id: '/e/$hash',
  path: '/e/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const PortugalMitMichaelEditRoute = PortugalMitMichaelEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PortugalMitMichaelRoute,
} as any)
const PortugalUrlaubEditRoute = PortugalUrlaubEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PortugalUrlaubRoute,
} as any)
const SHashRoute = SHashRouteImport.update({
  id: '/s/$hash',
  path: '/s/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const THashRoute = THashRouteImport.update({
  id: '/t/$hash',
  path: '/t/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleCallbackRoute = ApiGoogleCallbackRouteImport.update({
  id: '/api/google/callback',
  path: '/api/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleStartRoute = ApiGoogleStartRouteImport.update({
  id: '/api/google/start',
  path: '/api/google/start',
  getParentRoute: () => rootRouteImport,
} as any)
const DHashDayIdRoute = DHashDayIdRouteImport.update({
  id: '/d/$hash/$dayId',
  path: '/d/$hash/$dayId',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaHashIdRoute = MediaHashIdRouteImport.update({
  id: '/media/$hash/$id',
  path: '/media/$hash/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PortugalMitMichaelEditSettingsRoute =
  PortugalMitMichaelEditSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => PortugalMitMichaelEditRoute,
  } as any)
const PortugalUrlaubEditSettingsRoute =
  PortugalUrlaubEditSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => PortugalUrlaubEditRoute,
  } as any)
const THashEditRoute = THashEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => THashRoute,
} as any)
const THashEditSettingsRoute = THashEditSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => THashEditRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/portugal-mit-michael': typeof PortugalMitMichaelRouteWithChildren
  '/portugal-urlaub': typeof PortugalUrlaubRouteWithChildren
  '/e/$hash': typeof EHashRoute
  '/portugal-mit-michael/edit': typeof PortugalMitMichaelEditRouteWithChildren
  '/portugal-urlaub/edit': typeof PortugalUrlaubEditRouteWithChildren
  '/s/$hash': typeof SHashRoute
  '/t/$hash': typeof THashRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/google/start': typeof ApiGoogleStartRoute
  '/d/$hash/$dayId': typeof DHashDayIdRoute
  '/media/$hash/$id': typeof MediaHashIdRoute
  '/portugal-mit-michael/edit/settings': typeof PortugalMitMichaelEditSettingsRoute
  '/portugal-urlaub/edit/settings': typeof PortugalUrlaubEditSettingsRoute
  '/t/$hash/edit': typeof THashEditRouteWithChildren
  '/t/$hash/edit/settings': typeof THashEditSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/portugal-mit-michael': typeof PortugalMitMichaelRouteWithChildren
  '/portugal-urlaub': typeof PortugalUrlaubRouteWithChildren
  '/e/$hash': typeof EHashRoute
  '/portugal-mit-michael/edit': typeof PortugalMitMichaelEditRouteWithChildren
  '/portugal-urlaub/edit': typeof PortugalUrlaubEditRouteWithChildren
  '/s/$hash': typeof SHashRoute
  '/t/$hash': typeof THashRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/google/start': typeof ApiGoogleStartRoute
  '/d/$hash/$dayId': typeof DHashDayIdRoute
  '/media/$hash/$id': typeof MediaHashIdRoute
  '/portugal-mit-michael/edit/settings': typeof PortugalMitMichaelEditSettingsRoute
  '/portugal-urlaub/edit/settings': typeof PortugalUrlaubEditSettingsRoute
  '/t/$hash/edit': typeof THashEditRouteWithChildren
  '/t/$hash/edit/settings': typeof THashEditSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/portugal-mit-michael': typeof PortugalMitMichaelRouteWithChildren
  '/portugal-urlaub': typeof PortugalUrlaubRouteWithChildren
  '/e/$hash': typeof EHashRoute
  '/portugal-mit-michael/edit': typeof PortugalMitMichaelEditRouteWithChildren
  '/portugal-urlaub/edit': typeof PortugalUrlaubEditRouteWithChildren
  '/s/$hash': typeof SHashRoute
  '/t/$hash': typeof THashRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/google/start': typeof ApiGoogleStartRoute
  '/d/$hash/$dayId': typeof DHashDayIdRoute
  '/media/$hash/$id': typeof MediaHashIdRoute
  '/portugal-mit-michael/edit/settings': typeof PortugalMitMichaelEditSettingsRoute
  '/portugal-urlaub/edit/settings': typeof PortugalUrlaubEditSettingsRoute
  '/t/$hash/edit': typeof THashEditRouteWithChildren
  '/t/$hash/edit/settings': typeof THashEditSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/portugal-mit-michael'
    | '/portugal-urlaub'
    | '/e/$hash'
    | '/portugal-mit-michael/edit'
    | '/portugal-urlaub/edit'
    | '/s/$hash'
    | '/t/$hash'
    | '/api/auth/$'
    | '/api/google/callback'
    | '/api/google/start'
    | '/d/$hash/$dayId'
    | '/media/$hash/$id'
    | '/portugal-mit-michael/edit/settings'
    | '/portugal-urlaub/edit/settings'
    | '/t/$hash/edit'
    | '/t/$hash/edit/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/portugal-mit-michael'
    | '/portugal-urlaub'
    | '/e/$hash'
    | '/portugal-mit-michael/edit'
    | '/portugal-urlaub/edit'
    | '/s/$hash'
    | '/t/$hash'
    | '/api/auth/$'
    | '/api/google/callback'
    | '/api/google/start'
    | '/d/$hash/$dayId'
    | '/media/$hash/$id'
    | '/portugal-mit-michael/edit/settings'
    | '/portugal-urlaub/edit/settings'
    | '/t/$hash/edit'
    | '/t/$hash/edit/settings'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/portugal-mit-michael'
    | '/portugal-urlaub'
    | '/e/$hash'
    | '/portugal-mit-michael/edit'
    | '/portugal-urlaub/edit'
    | '/s/$hash'
    | '/t/$hash'
    | '/api/auth/$'
    | '/api/google/callback'
    | '/api/google/start'
    | '/d/$hash/$dayId'
    | '/media/$hash/$id'
    | '/portugal-mit-michael/edit/settings'
    | '/portugal-urlaub/edit/settings'
    | '/t/$hash/edit'
    | '/t/$hash/edit/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  PortugalMitMichaelRoute: typeof PortugalMitMichaelRouteWithChildren
  PortugalUrlaubRoute: typeof PortugalUrlaubRouteWithChildren
  EHashRoute: typeof EHashRoute
  SHashRoute: typeof SHashRoute
  THashRoute: typeof THashRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiGoogleCallbackRoute: typeof ApiGoogleCallbackRoute
  ApiGoogleStartRoute: typeof ApiGoogleStartRoute
  DHashDayIdRoute: typeof DHashDayIdRoute
  MediaHashIdRoute: typeof MediaHashIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portugal-mit-michael': {
      id: '/portugal-mit-michael'
      path: '/portugal-mit-michael'
      fullPath: '/portugal-mit-michael'
      preLoaderRoute: typeof PortugalMitMichaelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portugal-urlaub': {
      id: '/portugal-urlaub'
      path: '/portugal-urlaub'
      fullPath: '/portugal-urlaub'
      preLoaderRoute: typeof PortugalUrlaubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$hash': {
      id: '/e/$hash'
      path: '/e/$hash'
      fullPath: '/e/$hash'
      preLoaderRoute: typeof EHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portugal-mit-michael/edit': {
      id: '/portugal-mit-michael/edit'
      path: '/edit'
      fullPath: '/portugal-mit-michael/edit'
      preLoaderRoute: typeof PortugalMitMichaelEditRouteImport
      parentRoute: typeof PortugalMitMichaelRoute
    }
    '/portugal-urlaub/edit': {
      id: '/portugal-urlaub/edit'
      path: '/edit'
      fullPath: '/portugal-urlaub/edit'
      preLoaderRoute: typeof PortugalUrlaubEditRouteImport
      parentRoute: typeof PortugalUrlaubRoute
    }
    '/s/$hash': {
      id: '/s/$hash'
      path: '/s/$hash'
      fullPath: '/s/$hash'
      preLoaderRoute: typeof SHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$hash': {
      id: '/t/$hash'
      path: '/t/$hash'
      fullPath: '/t/$hash'
      preLoaderRoute: typeof THashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/callback': {
      id: '/api/google/callback'
      path: '/api/google/callback'
      fullPath: '/api/google/callback'
      preLoaderRoute: typeof ApiGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/start': {
      id: '/api/google/start'
      path: '/api/google/start'
      fullPath: '/api/google/start'
      preLoaderRoute: typeof ApiGoogleStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$hash/$dayId': {
      id: '/d/$hash/$dayId'
      path: '/d/$hash/$dayId'
      fullPath: '/d/$hash/$dayId'
      preLoaderRoute: typeof DHashDayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$hash/$id': {
      id: '/media/$hash/$id'
      path: '/media/$hash/$id'
      fullPath: '/media/$hash/$id'
      preLoaderRoute: typeof MediaHashIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portugal-mit-michael/edit/settings': {
      id: '/portugal-mit-michael/edit/settings'
      path: '/settings'
      fullPath: '/portugal-mit-michael/edit/settings'
      preLoaderRoute: typeof PortugalMitMichaelEditSettingsRouteImport
      parentRoute: typeof PortugalMitMichaelEditRoute
    }
    '/portugal-urlaub/edit/settings': {
      id: '/portugal-urlaub/edit/settings'
      path: '/settings'
      fullPath: '/portugal-urlaub/edit/settings'
      preLoaderRoute: typeof PortugalUrlaubEditSettingsRouteImport
      parentRoute: typeof PortugalUrlaubEditRoute
    }
    '/t/$hash/edit': {
      id: '/t/$hash/edit'
      path: '/edit'
      fullPath: '/t/$hash/edit'
      preLoaderRoute: typeof THashEditRouteImport
      parentRoute: typeof THashRoute
    }
    '/t/$hash/edit/settings': {
      id: '/t/$hash/edit/settings'
      path: '/settings'
      fullPath: '/t/$hash/edit/settings'
      preLoaderRoute: typeof THashEditSettingsRouteImport
      parentRoute: typeof THashEditRoute
    }
  }
}

interface PortugalMitMichaelEditRouteChildren {
  PortugalMitMichaelEditSettingsRoute: typeof PortugalMitMichaelEditSettingsRoute
}

const PortugalMitMichaelEditRouteChildren: PortugalMitMichaelEditRouteChildren =
  {
    PortugalMitMichaelEditSettingsRoute: PortugalMitMichaelEditSettingsRoute,
  }

const PortugalMitMichaelEditRouteWithChildren =
  PortugalMitMichaelEditRoute._addFileChildren(
    PortugalMitMichaelEditRouteChildren,
  )

interface PortugalMitMichaelRouteChildren {
  PortugalMitMichaelEditRoute: typeof PortugalMitMichaelEditRouteWithChildren
}

const PortugalMitMichaelRouteChildren: PortugalMitMichaelRouteChildren = {
  PortugalMitMichaelEditRoute: PortugalMitMichaelEditRouteWithChildren,
}

const PortugalMitMichaelRouteWithChildren =
  PortugalMitMichaelRoute._addFileChildren(PortugalMitMichaelRouteChildren)

interface PortugalUrlaubEditRouteChildren {
  PortugalUrlaubEditSettingsRoute: typeof PortugalUrlaubEditSettingsRoute
}

const PortugalUrlaubEditRouteChildren: PortugalUrlaubEditRouteChildren = {
  PortugalUrlaubEditSettingsRoute: PortugalUrlaubEditSettingsRoute,
}

const PortugalUrlaubEditRouteWithChildren =
  PortugalUrlaubEditRoute._addFileChildren(PortugalUrlaubEditRouteChildren)

interface PortugalUrlaubRouteChildren {
  PortugalUrlaubEditRoute: typeof PortugalUrlaubEditRouteWithChildren
}

const PortugalUrlaubRouteChildren: PortugalUrlaubRouteChildren = {
  PortugalUrlaubEditRoute: PortugalUrlaubEditRouteWithChildren,
}

const PortugalUrlaubRouteWithChildren = PortugalUrlaubRoute._addFileChildren(
  PortugalUrlaubRouteChildren,
)

interface THashEditRouteChildren {
  THashEditSettingsRoute: typeof THashEditSettingsRoute
}

const THashEditRouteChildren: THashEditRouteChildren = {
  THashEditSettingsRoute: THashEditSettingsRoute,
}

const THashEditRouteWithChildren = THashEditRoute._addFileChildren(
  THashEditRouteChildren,
)

interface THashRouteChildren {
  THashEditRoute: typeof THashEditRouteWithChildren
}

const THashRouteChildren: THashRouteChildren = {
  THashEditRoute: THashEditRouteWithChildren,
}

const THashRouteWithChildren = THashRoute._addFileChildren(THashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  PortugalMitMichaelRoute: PortugalMitMichaelRouteWithChildren,
  PortugalUrlaubRoute: PortugalUrlaubRouteWithChildren,
  EHashRoute: EHashRoute,
  SHashRoute: SHashRoute,
  THashRoute: THashRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiGoogleCallbackRoute: ApiGoogleCallbackRoute,
  ApiGoogleStartRoute: ApiGoogleStartRoute,
  DHashDayIdRoute: DHashDayIdRoute,
  MediaHashIdRoute: MediaHashIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
