/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortugalMitMichaelRouteImport } from './routes/portugal-mit-michael'
import { Route as EHashRouteImport } from './routes/e.$hash'
import { Route as THashRouteImport } from './routes/t.$hash'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortugalMitMichaelRoute = PortugalMitMichaelRouteImport.update({
  id: '/portugal-mit-michael',
  path: '/portugal-mit-michael',
  getParentRoute: () => rootRouteImport,
} as any)
const EHashRoute = EHashRouteImport.update({
  id: '/e/$hash',
  path: '/e/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const THashRoute = THashRouteImport.update({
  id: '/t/$hash',
  path: '/t/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/portugal-mit-michael': typeof PortugalMitMichaelRoute
  '/e/$hash': typeof EHashRoute
  '/t/$hash': typeof THashRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/portugal-mit-michael': typeof PortugalMitMichaelRoute
  '/e/$hash': typeof EHashRoute
  '/t/$hash': typeof THashRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/portugal-mit-michael': typeof PortugalMitMichaelRoute
  '/e/$hash': typeof EHashRoute
  '/t/$hash': typeof THashRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/portugal-mit-michael'
    | '/e/$hash'
    | '/t/$hash'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/portugal-mit-michael'
    | '/e/$hash'
    | '/t/$hash'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/portugal-mit-michael'
    | '/e/$hash'
    | '/t/$hash'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  PortugalMitMichaelRoute: typeof PortugalMitMichaelRoute
  EHashRoute: typeof EHashRoute
  THashRoute: typeof THashRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portugal-mit-michael': {
      id: '/portugal-mit-michael'
      path: '/portugal-mit-michael'
      fullPath: '/portugal-mit-michael'
      preLoaderRoute: typeof PortugalMitMichaelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$hash': {
      id: '/e/$hash'
      path: '/e/$hash'
      fullPath: '/e/$hash'
      preLoaderRoute: typeof EHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$hash': {
      id: '/t/$hash'
      path: '/t/$hash'
      fullPath: '/t/$hash'
      preLoaderRoute: typeof THashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  PortugalMitMichaelRoute: PortugalMitMichaelRoute,
  EHashRoute: EHashRoute,
  THashRoute: THashRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
